local colors = require 'colors.colors'

return {
  { '@annotation', { fg = colors.base0F } },
  { '@attribute', { fg = colors.base0A } },
  { '@character', { fg = colors.base08 } },
  { '@constant.builtin', { fg = colors.base08 } },
  { '@constant.macro', { fg = colors.base08 } },
  { '@error', { fg = colors.base08 } },
  { '@exception', { fg = colors.base08, italic = true } },
  { '@float', { fg = colors.base08 } },
  { '@keyword.function', { fg = colors.base0E, italic = true } },
  { '@keyword.return', { fg = colors.base0E, italic = true } },
  { '@function.builtin', { fg = colors.base0D } },
  { '@function.macro', { fg = colors.base08 } },
  { '@keyword.operator', { fg = colors.base0E, italic = true } },
  { '@method', { fg = colors.base0D } },
  { '@namespace', { fg = colors.base07 } },
  { '@none', { fg = colors.base05 } },
  { '@parameter', { fg = colors.base08 } },
  { '@parameter.reference', { fg = colors.base05 } },
  { '@punctuation.bracket', { fg = colors.base0C } },
  { '@punctuation.delimiter', { fg = colors.base0C } },
  { '@punctuation.special', { fg = colors.base08 } },
  { '@string.regex', { fg = colors.base0C } },
  { '@string.escape', { fg = colors.base0C } },
  { '@symbol', { fg = colors.base0B } },
  { '@tag.delimiter', { fg = colors.base0F } },
  { '@text', { fg = colors.base05 } },
  { '@text.strong', { bold = true } },
  { '@text.emphasis', { fg = colors.base09 } },
  { '@text.strike', { fg = colors.base01, strikethrough = true } },
  { '@text.literal', { fg = colors.base09 } },
  { '@text.uri', { fg = colors.base09, underline = true } },
  { '@type.builtin', { fg = colors.base0E, italic = true } },
  { '@variable.builtin', { fg = colors.base05 } },
  { '@variable', { fg = colors.base05 } },
  { '@definition', { sp = colors.base04, underline = true } },
  { '@field', { fg = colors.base0D } },
  { '@property', { fg = colors.base07 } },
  { '@constructor', { fg = colors.base07 } },

  { 'Boolean', { fg = colors.base08, italic = true } },
  { 'Character', { fg = colors.base08 } },
  { 'Conditional', { fg = colors.base0E } },
  { 'Constant', { fg = colors.base08 } },
  { 'Define', { fg = colors.base0E } },
  { 'Delimiter', { fg = colors.base0F } },
  { 'Float', { fg = colors.base08 } },
  { 'Variable', { fg = colors.base05 } },
  { 'Function', { fg = colors.base0D } },
  { 'Identifier', { fg = colors.base08 } },
  { 'Include', { fg = colors.base0E, italic = true } },
  { 'Keyword', { fg = colors.base0E, italic = true } },
  { 'Label', { fg = colors.base08 } },
  { 'Number', { fg = colors.base08 } },
  { 'Operator', { fg = colors.base0C } },
  { 'PreProc', { fg = colors.base0A } },
  { 'Repeat', { fg = colors.base0E, italic = true } },
  { 'Special', { fg = colors.base0C } },
  { 'SpecialChar', { fg = colors.base0F } },
  { 'Statement', { fg = colors.base08 } },
  { 'StorageClass', { fg = colors.base0A } },
  { 'String', { fg = colors.base0B } },
  { 'Structure', { fg = colors.base0E } },
  { 'Tag', { fg = colors.base0A } },
  { 'Todo', { fg = colors.base0A, bg = colors.base02 } },
  { 'Type', { fg = colors.base07 } },
  { 'Typedef', { fg = colors.base0A } },

  { '@class_declaration', { fg = colors.base0B } },
  { '@interface_declaration', { fg = colors.base0D } },
  { '@function_call', { fg = colors.base0B } },
  { '@attribute_parameter', { fg = colors.base0D } },

  -- html
  { 'htmlTag', { fg = colors.base0C } },
  { 'htmlEndTag', { fg = colors.base0C } },
  { 'htmlTagN', { fg = colors.base0C } },
  { 'htmlTagName', { fg = colors.base0C } },
  { 'htmlArg', { fg = colors.base0B } },
  { 'htmlString', { fg = colors.base0A } },

  -- json
  { 'JsonScalar', { fg = colors.base0E } },

  -- yaml
  { '@field.yaml', { fg = colors.base08 } },

  -- php
  { '@attribute.php', { fg = colors.base0D } },
  { '@string.php', { fg = colors.base0A } },
  { '@variable.php', { fg = colors.base0C } },
  { '@variable.builtin.php', { fg = colors.base0C } },
  { '@variable.php', { fg = colors.base0C } },
  { '@function.php', { fg = colors.base0B } },
  { '@const.builtin.php', { fg = colors.base0E } },
  { '@exception.php', { fg = colors.base0E, italic = true } },
  { '@error.php', { fg = colors.base05 } },

  -- twig
  { '@tag.twig', { fg = colors.base0E } },
  { '@tag.delimiter.twig', { fg = colors.base07 } },
  { '@string.twig', { fg = colors.base0A } },
  { '@variable.twig', { fg = colors.base07 } },
  { '@attribute.twig', { fg = colors.base07 } },

  -- xml
  { 'xmlTagName', { fg = colors.base0C } },
  { 'xmlTag', { fg = colors.base0C } },
  { 'xmlAttrib', { fg = colors.base0B } },
  { 'xmlString', { fg = colors.base0A } },

  -- html
  { '@tag.html', { fg = colors.base0C } },
  { '@tag.delimiter.html', { fg = colors.base0C } },
  { '@tag.attribute.html', { fg = colors.base0B } },
  { '@string.html', { fg = colors.base0A } },
  { '@constant.html', { fg = colors.base0C } },

  -- makrdown
  { '@punctuation.special.markdown', { fg = colors.base04 } },
}
