local colors = require 'colorscheme.colors'

return {
  { 'CmpItemAbbr', { fg = colors.base05 } },
  { 'CmpItemAbbrMatch', { fg = colors.base0D, bold = true } },
  { 'CmpBorder', { fg = colors.base03 } },
  { 'CmPmenu', { bg = colors.base00 } },

  { 'CmpDocumentationBorder', { fg = colors.base05, bg = colors.base00 } },
  { 'CmpDocumentation', { fg = colors.base05, bg = colors.base00 } },

  { 'CmpItemAbbr', { fg = colors.base05, bg = colors.base00 } },
  { 'CmpItemAbbrDeprecated', { fg = colors.base03, strikethrough = true } },
  { 'CmpItemAbbrMatch', { fg = colors.base0D } },
  { 'CmpItemAbbrMatchFuzzy', { fg = colors.base0D } },
  { 'CmpItemKindDefault', { fg = colors.base05 } },
  { 'CmpItemMenu', { fg = colors.base04 } },
  { 'CmpItemKindKeyword', { fg = colors.base0E } },
  { 'CmpItemKindVariable', { fg = colors.base08 } },
  { 'CmpItemKindConstant', { fg = colors.base09 } },
  { 'CmpItemKindReference', { fg = colors.base08 } },
  { 'CmpItemKindValue', { fg = colors.base09 } },
  { 'CmpItemKindFunction', { fg = colors.base0D } },
  { 'CmpItemKindMethod', { fg = colors.base0D } },
  { 'CmpItemKindConstructor', { fg = colors.base0D } },
  { 'CmpItemKindClass', { fg = colors.base0A } },
  { 'CmpItemKindInterface', { fg = colors.base0A } },
  { 'CmpItemKindStruct', { fg = colors.base0A } },
  { 'CmpItemKindEvent', { fg = colors.base0A } },
  { 'CmpItemKindEnum', { fg = colors.base0A } },
  { 'CmpItemKindUnit', { fg = colors.base0A } },
  { 'CmpItemKindModule', { fg = colors.base05 } },
  { 'CmpItemKindProperty', { fg = colors.base08 } },
  { 'CmpItemKindField', { fg = colors.base08 } },
  { 'CmpItemKindTypeParameter', { fg = colors.base0A } },
  { 'CmpItemKindEnumMember', { fg = colors.base0A } },
  { 'CmpItemKindOperator', { fg = colors.base05 } },
  { 'CmpItemKindSnippet', { fg = colors.base0F } },
  { 'CmpItemKindIdentifier', { fg = colors.base08 } },
  { 'CmpItemKindText', { fg = colors.base0B } },
  { 'CmpItemKindStructure', { fg = colors.base0E } },
  { 'CmpItemKindType', { fg = colors.base0A } },
  { 'CmpItemKindFolder', { fg = colors.base07 } },
  { 'CmpItemKindFile', { fg = colors.base07 } },
  { 'CmpItemKindColor', { fg = colors.base0F } },
}
