local colors = require 'colorscheme.colors'

return {
  { 'Normal', { fg = colors.base06, bg = colors.base01 } },
  { 'Bold', { bold = true } },
  { 'Directory', { fg = colors.base0D } },
  { 'ErrorMsg', { fg = colors.base08, bg = colors.base01 } },
  { 'Exception', { fg = colors.base08 } },
  { 'FoldColumn', { fg = colors.base0C, bg = colors.base01 } },
  { 'Folded', { fg = colors.base04, bg = colors.base11 } },
  { 'IncSearch', { fg = colors.base02, bg = colors.base09 } },
  { 'Italic', {} },
  { 'Macro', { fg = colors.base08 } },
  { 'MatchParen', { bg = colors.base04 } },
  { 'ModeMsg', { fg = colors.base0B } },
  { 'MoreMsg', { fg = colors.base0B } },
  { 'Question', { fg = colors.base0D } },
  { 'Search', { fg = colors.base02, bg = colors.base0A } },
  { 'Substitute', { fg = colors.base02, bg = colors.base0A } },
  { 'SpecialKey', { fg = colors.base04 } },
  { 'TooLong', { fg = colors.base08 } },
  { 'Underlined', { fg = colors.base08 } },
  { 'Visual', { bg = colors.base04 } },
  { 'VisualNOS', { fg = colors.base08 } },
  { 'WarningMsg', { fg = colors.base08 } },
  { 'WildMenu', { fg = colors.base08, bg = colors.base0A } },
  { 'Title', { fg = colors.base0D } },
  { 'Cursor', { fg = colors.base00, bg = colors.base06 } },
  { 'NonText', { fg = colors.base04 } },
  { 'LineNr', { fg = colors.base04, bg = colors.base01 } },
  { 'SignColumn', { fg = colors.base05, bg = colors.base01 } },
  { 'StatusLine', { fg = colors.base06, bg = colors.base03 } },
  { 'StatusLineNC', { fg = colors.base05, bg = colors.base02 } },
  { 'WinBar', { fg = colors.base06 } },
  { 'WinBarNC', { fg = colors.base05 } },
  { 'VertSplit', { fg = colors.base06, bg = colors.base01 } },
  { 'ColorColumn', { bg = colors.base02 } },
  { 'CursorColumn', { bg = colors.base02 } },
  { 'CursorLine', { bg = colors.base02 } },
  { 'CursorLineNr', { fg = colors.base05, bg = colors.base02 } },
  { 'QuickFixLine', { bg = colors.base02 } },
  { 'PMenu', { fg = colors.base06, bg = colors.base02 } },
  { 'PMenuSel', { fg = colors.base02, bg = colors.base0D } },
  { 'TabLine', { fg = colors.base04, bg = colors.base02 } },
  { 'TabLineFill', { fg = colors.base04, bg = colors.base02 } },
  { 'TabLineSel', { fg = colors.base0B, bg = colors.base02 } },
  { 'NormalFloat', { fg = colors.base06, bg = colors.base00 } },
  { 'FloatBorder', { fg = colors.base04, bg = colors.base01 } },
  { 'NormalNC', { fg = colors.base06, bg = colors.base01 } },
  { 'TermCursor', { fg = colors.base01, bg = colors.base06 } },
  { 'TermCursorNC', { fg = colors.base01, bg = colors.base06 } },
  { 'NvimInternalError', { fg = colors.base01, bg = colors.base08 } },
  { 'SpellBad', { undercurl = true, sp = colors.base08 } },
  { 'SpellLocal', { undercurl = true, sp = colors.base0C } },
  { 'SpellCap', { undercurl = true, sp = colors.base0D } },
  { 'SpellRare', { undercurl = true, sp = colors.base0E } },

  { 'PmenuSbar', { bg = colors.base03 } },
  { 'PmenuThumb', { bg = colors.base04 } },
  { 'WinSeparator', { fg = colors.base03 } },
}
