local colors = require 'colorscheme.colors'

return {
  { 'PMenuSel', { fg = colors.base02, bg = colors.base0D } },

  { '@variable.sql', { fg = colors.base07 } },
  { '@field.sql', { fg = colors.base07 } },

  { '@tag', { fg = colors.base0D } },
  { '@tag.delimiter', { fg = colors.base0D } },

  { '@property.yaml', { fg = colors.base08 } },
  { '@constant.bash', { fg = colors.base08 } },
  { '@property.json', { fg = colors.base08 } },

  { '@punctuation.delimiter', { fg = colors.base0C } },

  { '@tag.twig', { fg = colors.base0E } },

  { '@include.tsx', { fg = colors.base0E } },
  { '@punctuation.bracket.tsx', { fg = colors.base0C } },
  { '@function.call.tsx', { fg = colors.base0B } },
  { '@method.call.tsx', { fg = colors.base0B } },
  { '@property.tsx', { fg = colors.base07 } },
  { '@type.tsx', { fg = colors.base07 } },
  { '@type.builtin.tsx', { fg = colors.base0E } },
  { '@variable.tsx', { fg = colors.base0C } },
  { '@parameter.tsx', { fg = colors.base0C } },
  { '@number.tsx', { fg = colors.base08 } },
  { '@constant.builtin.tsx', { fg = colors.base08 } },
  { '@constant.tsx', { fg = colors.base08 } },
  { '@boolean.tsx', { fg = colors.base08 } },
  { '@operator.tsx', { fg = colors.base0C } },

  { '@include.typescript', { fg = colors.base0E } },
  { '@punctuation.bracket.typescript', { fg = colors.base0C } },
  { '@function.call.typescript', { fg = colors.base0B } },
  { '@method.call.typescript', { fg = colors.base0B } },
  { '@property.typescript', { fg = colors.base07 } },
  { '@type.typescript', { fg = colors.base07 } },
  { '@type.builtin.typescript', { fg = colors.base0E } },
  { '@variable.typescript', { fg = colors.base0C } },
  { '@parameter.typescript', { fg = colors.base0C } },
  { '@number.typescript', { fg = colors.base08 } },
  { '@constant.builtin.typescript', { fg = colors.base08 } },
  { '@constant.typescript', { fg = colors.base08 } },
  { '@boolean.typescript', { fg = colors.base08 } },
  { '@operator.typescript', { fg = colors.base0C } },

  -- { '@string.javascript', { fg = colors.base0A } },
  -- { '@include.javascript', { fg = colors.base0E } },
  -- { '@punctuation.bracket.javascript', { fg = colors.base0C } },
  -- { '@function.call.javascript', { fg = colors.base0B } },
  -- { '@function.method.call.javascript', { fg=colors.base0B } },
  -- { '@function.javascript', { fg = colors.base0D } },
  -- { '@method.call.javascript', { fg = colors.base0B } },
  -- { '@property.javascript', { fg = colors.base07 } },
  -- { '@type.javascript', { fg = colors.base07 } },
  -- { '@type.builtin.javascript', { fg = colors.base0E } },
  -- { '@variable.javascript', { fg = colors.base0C } },
  -- { '@variable.member.javascript', { fg = colors.base07 } },
  -- { '@variable.builtin.javascript', { fg = colors.base0C } },
  -- { '@variable.parameter.javascript', { fg = colors.base0C } },
  -- { '@parameter.javascript', { fg = colors.base0C } },
  -- { '@number.javascript', { fg = colors.base08 } },
  -- { '@constant.builtin.javascript', { fg = colors.base08 } },
  -- { '@constant.javascript', { fg = colors.base08 } },
  -- { '@boolean.javascript', { fg = colors.base08 } },
  -- { '@operator.javascript', { fg = colors.base0C } },

  { '@string.php', { fg = colors.base0A } },
  { '@property.php', { fg = colors.base07 } },
  { '@variable.php', { fg = colors.base0C } },
  { '@function.php', { fg = colors.base0B } },
  { '@constructor.php', { fg = colors.base07 } },
  { '@constant.php', { fg = colors.base08 } },
  { '@constant.builtin.php', { fg = colors.base08 } },
  { '@number.php', { fg = colors.base08 } },
  { '@boolean.php', { fg = colors.base08 } },
  { '@type.php', { fg = colors.base07 } },
  { '@type.builtin.php', { fg = colors.base0E } },
  { '@include.php', { fg = colors.base0E } },
  { '@namespace.php', { fg = colors.base07 } },
  { '@function.call.php', { fg = colors.base0B } },
  { '@variable.builtin.php', { fg = colors.base0C } },
  { '@exception.php', { fg = colors.base0E } },
  { '@operator.php', { fg = colors.base0C } },
  { '@punctuation.delimiter.php', { fg = colors.base0C } },
  { '@punctuation.bracket.php', { fg = colors.base0C } },
  { '@error.php', { fg = colors.base06 } },
  { '@parameter.php', { fg = colors.base0D } },
  { '@attribute.php', { fg = colors.base0D } },
  { '@type.phpdoc', { fg = colors.base07 } },

  { '@module.go', { fg = colors.base06 } },
}
